### ISSUE TITLE
Crash on android (emulator and real device) after joinChannelSuccess

### ISSUE THREAD

**Issue by kolyuchii** [syanbo/react-native-agora#222]
"react-native": "0.62.2",
"react-native-agora": "^2.9.1-alpha.6",

Error
```
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: sampleRate
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:110)
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:114)
       at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:157)
       at com.syan.agora.AgoraModule.startAudioRecording(AgoraModule.java:1899)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)
```

JS CODE 
```
        RtcEngine.on('joinChannelSuccess', (data) => {
            console.log('joinChannelSuccess', data);
        });
        RtcEngine.init(AGORA_BROADCASTER_CONFIG);
```

`joinChannelSuccess {"channel": "9LazmRjHatajopd45woRy74hlCs2", "elapsed": 612, "uid": 6662}
`

**Comment by kolyuchii** [comment]
Sorry guys I'm blind)))
Forgot to set sampleRate in the JS

```
            RtcEngine.startAudioRecording({
                filepath: this.audioPath,
                sampleRate: 48000,
                quality: 2,
            });
```
