### ISSUE TITLE
Android - missing lib/index.js in react-native-agora npm version 3.0.1-beta.6

### ISSUE THREAD

**Issue by mahpat16** [syanbo/react-native-agora#228]
When I added the react-native-agora version 3.0.1-beta.6 package to my Android project, I get the following error. It looks like the npm package is missing the lib/index.js file.

error: Error: While trying to resolve module `react-native-agora` from file `/home/anisha/projects/gatherrn/src/components/agora/Video.tsx`, the package `/home/anisha/projects/gatherrn/node_modules/react-native-agora/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/anisha/projects/gatherrn/node_modules/react-native-agora/lib/index.js`. Indeed, none of these files exist:
  * /home/anisha/projects/gatherrn/node_modules/react-native-agora/lib/index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /home/anisha/projects/gatherrn/node_modules/react-native-agora/lib/index.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (/home/anisha/projects/gatherrn/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/home/anisha/projects/gatherrn/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/home/anisha/projects/gatherrn/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /home/anisha/projects/gatherrn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/home/anisha/projects/gatherrn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /home/anisha/projects/gatherrn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/anisha/projects/gatherrn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/home/anisha/projects/gatherrn/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)

The file is missing from the npm package.

**Comment by LichKing-2234** [comment]
I have published the new version 3.0.1-beta.7.
